runtime: java11
entrypoint: java -jar demo-0.0.1-SNAPSHOT.war com.example.demo.DemoApplication
env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: IGP3D1quBApKu888
  CLOUD_SQL_DATABASE_NAME: postgres
  CLOUD_SQL_CONNECTION_NAME: fii-covidtracker:europe-west3:fii-covidtracker-db
instance_class: F4